In [1]:
# Part I - Importing Libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# Part II - Data Preprocessing
#Importing library
db = pd.read_csv('Churn_Modelling.csv')
X = db.iloc[:, 3:-1].values
y = db.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


In [5]:
#Encoding categorical data - on gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
#OneHotEncoding on geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
#Splitting the dataset into train and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [9]:
#Feature SCaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Part III - BUilding your ANN

ann = tf.keras.models.Sequential()

In [11]:
#adding the input layer and hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
#Another hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
#Add ouput layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [14]:
# Part IV - Training the ANN
#Compilation of ANN using optimizer

ann.compile(optimizer = 'RMSprop' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [15]:
#training the ann

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
235/235 [==============================] - 2s 7ms/step - loss: 0.5103 - accuracy: 0.7963
Epoch 2/100
235/235 [==============================] - 1s 6ms/step - loss: 0.4782 - accuracy: 0.7963
Epoch 3/100
235/235 [==============================] - 1s 6ms/step - loss: 0.4588 - accuracy: 0.7963
Epoch 4/100
235/235 [==============================] - 2s 7ms/step - loss: 0.4450 - accuracy: 0.7963
Epoch 5/100
235/235 [==============================] - 2s 7ms/step - loss: 0.4367 - accuracy: 0.7963
Epoch 6/100
235/235 [==============================] - 2s 8ms/step - loss: 0.4325 - accuracy: 0.7963
Epoch 7/100
235/235 [==============================] - 2s 8ms/step - loss: 0.4299 - accuracy: 0.8051
Epoch 8/100
235/235 [==============================] - 2s 7ms/step - loss: 0.4281 - accuracy: 0.8124
Epoch 9/100
235/235 [==============================] - 2s 8ms/step - loss: 0.4264 - accuracy: 0.8139
Epoch 10/100
235/235 [==============================] - 2s 9ms/step - loss: 0.4251 - accura

235/235 [==============================] - 1s 5ms/step - loss: 0.3360 - accuracy: 0.8627
Epoch 81/100
235/235 [==============================] - 1s 5ms/step - loss: 0.3359 - accuracy: 0.8639
Epoch 82/100
235/235 [==============================] - 2s 10ms/step - loss: 0.3358 - accuracy: 0.8647
Epoch 83/100
235/235 [==============================] - 2s 8ms/step - loss: 0.3357 - accuracy: 0.8635
Epoch 84/100
235/235 [==============================] - 2s 8ms/step - loss: 0.3356 - accuracy: 0.8651
Epoch 85/100
235/235 [==============================] - 2s 10ms/step - loss: 0.3352 - accuracy: 0.8629
Epoch 86/100
235/235 [==============================] - 2s 9ms/step - loss: 0.3354 - accuracy: 0.8628
Epoch 87/100
235/235 [==============================] - 2s 8ms/step - loss: 0.3355 - accuracy: 0.8629
Epoch 88/100
235/235 [==============================] - 2s 8ms/step - loss: 0.3355 - accuracy: 0.8643
Epoch 89/100
235/235 [==============================] - 2s 8ms/step - loss: 0.3352 - accuracy

In [16]:
#Predicting the result for one observation 
# Selected observation - France, credit_score = 600, gender is male, age=40, tenure=3, balance=60k we select that row.

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) 

#the probability that the given customer leaves is 19%.

#remove '>0.5' to get the probability value. False here depicts that the customer won't leave.

[[False]]


In [17]:
#Predicting the test results
y_prediction = ann.predict(X_test)
y_prediction = (y_prediction > 0.5)
print(np.concatenate((y_prediction.reshape(len(y_prediction),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [18]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_prediction)
print(cm)
accuracy_score(y_test, y_prediction)

[[1902   89]
 [ 251  258]]


0.864